<?php

declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/app/Core/Bootstrap.php';

use Addons\Game\Domain\BubblePracticeEngine;
use Addons\GameSessions\Application\ReplayVerifier;
use Addons\GameSessions\Application\SignedPracticeSessionService;
use App\Core\Security\HmacSigner;

function expectTrue(bool $condition, string $message): void
{
    if (!$condition) {
        throw new RuntimeException($message);
    }
}

function expectSame(mixed $expected, mixed $actual, string $message): void
{
    if ($expected !== $actual) {
        throw new RuntimeException($message . "\nExpected: " . var_export($expected, true) . "\nActual: " . var_export($actual, true));
    }
}

$secret = 'ci-only-secret-change-me-0123456789';
$sessionService = new SignedPracticeSessionService($secret, 900);
$issuedAt = 1700000000;
$session = $sessionService->issue(424242, $issuedAt);
$claims = $sessionService->verify($session['token'], $issuedAt + 30);

expectSame(424242, $claims['seed'], 'Signed session must preserve the server seed.');
expectSame('br-practice-1', $claims['rules_version'], 'Signed session must pin the rules version.');
expectTrue(strlen($session['token']) > 80, 'Signed session token must be non-empty.');

$game = BubblePracticeEngine::createGame(424242);
expectSame(
    'cvcgvgcmggg/gcgccvgvmvg/cvmmgcmgvgg/vmvvccgggcc/gcmvggcgmvm/vcmvggvcvcg/.........../.........../.........../.........../.........../...........',
    BubblePracticeEngine::boardSignature($game['board']),
    'PHP engine must match the published deterministic seed vector.',
);

$replay = [
    'protocol_version' => 'br-replay-v1',
    'rules_version' => BubblePracticeEngine::RULES_VERSION,
    'mode' => 'practice',
    'value_type' => 'virtual',
    'seed' => 424242,
    'rows' => BubblePracticeEngine::DEFAULT_ROWS,
    'cols' => BubblePracticeEngine::DEFAULT_COLS,
    'initial_board_signature' => BubblePracticeEngine::boardSignature($game['board']),
    'shots' => [],
];

for ($index = 0; $index < 4; $index++) {
    $row = $index;
    $col = ($index * 3) % $game['cols'];
    $before = $game;
    $applied = BubblePracticeEngine::applyShot($game, $row, $col);
    $game = $applied['game'];
    $replay['shots'][] = [
        'index' => $index,
        'row' => $row,
        'col' => $col,
        'color' => $before['current_color'],
        'outcome' => $applied['result']['outcome'],
        'score_delta' => $applied['result']['scoreDelta'],
        'score_after' => $game['score'],
        'combo_after' => $game['combo'],
        'misses_after' => $game['misses'],
        'penalty' => (bool) ($applied['result']['penalty'] ?? false),
        'penalty_rows_after' => $game['penalty_rows'],
        'shots_left_after' => $game['shots_left'],
        'board_count_after' => BubblePracticeEngine::boardCount($game['board']),
        'board_signature_after' => BubblePracticeEngine::boardSignature($game['board']),
    ];
}

$replay['final'] = [
    'score' => $game['score'],
    'status' => $game['status'],
    'combo' => $game['combo'],
    'best_combo' => $game['best_combo'],
    'misses' => $game['misses'],
    'penalty_rows' => $game['penalty_rows'],
    'shots_left' => $game['shots_left'],
    'board_count' => BubblePracticeEngine::boardCount($game['board']),
    'board_signature' => BubblePracticeEngine::boardSignature($game['board']),
];

$verification = (new ReplayVerifier())->verify($replay, $claims);
expectTrue($verification['valid'] === true, 'A deterministic replay generated by the server engine must verify.');
expectSame($game['score'], $verification['score'], 'Verified score must be server-derived.');
expectSame($game['best_combo'], $verification['best_combo'], 'Verified combo metrics must be server-derived.');

$replay['shots'][0]['score_after']++;
$tampered = (new ReplayVerifier())->verify($replay, $claims);
expectTrue($tampered['valid'] === false, 'A tampered score event must be rejected.');

$expiredCaught = false;
try {
    $sessionService->verify($session['token'], $issuedAt + 901);
} catch (Throwable) {
    $expiredCaught = true;
}
expectTrue($expiredCaught, 'Expired sessions must be rejected.');

$forgedCaught = false;
try {
    HmacSigner::verify($session['token'] . 'x', $secret);
} catch (Throwable) {
    $forgedCaught = true;
}
expectTrue($forgedCaught, 'Modified signatures must be rejected.');

echo "PHP protocol tests passed.\n";
